import { CreatorPreset } from '../types';

export const CREATOR_PRESETS: CreatorPreset[] = [
  {
    id: 'youtube_1080p',
    name: 'YouTube 1080p Full HD',
    category: 'video',
    outputFormat: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    quality: 'high',
    resolution: '1920x1080',
    videoBitrate: '8M',
    audioBitrate: '320k',
    audioSampleRate: 48000,
    fps: 60,
    maintainAspect: true,
  },
  {
    id: 'youtube_4k',
    name: 'YouTube 4K Ultra HD',
    category: 'video',
    outputFormat: 'mp4',
    videoCodec: 'hevc',
    audioCodec: 'aac',
    quality: 'high',
    resolution: '3840x2160',
    videoBitrate: '45M',
    audioBitrate: '320k',
    audioSampleRate: 48000,
    fps: 60,
    maintainAspect: true,
    requiresPro: true,
  },
  {
    id: 'tiktok_vertical',
    name: 'TikTok Vertical Video (9:16)',
    category: 'social',
    outputFormat: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    quality: 'high',
    resolution: '1080x1920',
    videoBitrate: '8M',
    audioBitrate: '256k',
    fps: 30,
    maintainAspect: true,
    aspectRatioMode: 'crop_fill',
  },
  {
    id: 'instagram_reel',
    name: 'Instagram Reel (9:16)',
    category: 'social',
    outputFormat: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    quality: 'high',
    resolution: '1080x1920',
    videoBitrate: '8M',
    audioBitrate: '256k',
    fps: 30,
    maintainAspect: true,
    aspectRatioMode: 'crop_fill',
  },
  {
    id: 'instagram_feed',
    name: 'Instagram Feed Video (1:1 / 4:5)',
    category: 'social',
    outputFormat: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    quality: 'high',
    resolution: '1080x1080',
    videoBitrate: '6M',
    audioBitrate: '192k',
    fps: 30,
    maintainAspect: true,
    aspectRatioMode: 'crop_fill',
  },
  {
    id: 'twitter_x',
    name: 'X / Twitter Video',
    category: 'social',
    outputFormat: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    resolution: '1920x1080',
    videoBitrate: '4M',
    audioBitrate: '192k',
    fps: 30,
    maintainAspect: true,
  },
  {
    id: 'discord_compress',
    name: 'Discord Compressed Video (<25MB)',
    category: 'social',
    outputFormat: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    resolution: '1280x720',
    videoBitrate: '1.8M',
    audioBitrate: '128k',
    fps: 30,
    maintainAspect: true,
  },
  {
    id: 'whatsapp_compress',
    name: 'WhatsApp Video (<16MB)',
    category: 'social',
    outputFormat: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    resolution: '854x480',
    videoBitrate: '1.2M',
    audioBitrate: '128k',
    fps: 24,
    maintainAspect: true,
  },
  {
    id: 'podcast_master',
    name: 'Podcast Audio Master (Stereo 256k)',
    category: 'audio',
    outputFormat: 'mp3',
    audioCodec: 'mp3',
    audioBitrate: '256k',
    audioSampleRate: 44100,
    audioChannels: 2,
  },
  {
    id: 'high_res_mp3',
    name: 'High-Quality MP3 (320kbps CBR)',
    category: 'audio',
    outputFormat: 'mp3',
    audioCodec: 'mp3',
    audioBitrate: '320k',
    audioSampleRate: 48000,
    audioChannels: 2,
  },
  {
    id: 'extract_audio',
    name: 'Lossless Audio Extraction',
    category: 'audio',
    outputFormat: 'wav',
    audioCodec: 'wav',
    audioSampleRate: 48000,
    audioChannels: 2,
  },
  {
    id: 'archive_master',
    name: 'Archive-Quality Master (ProRes / Lossless)',
    category: 'archive',
    outputFormat: 'mov',
    videoCodec: 'h264',
    audioCodec: 'flac',
    videoBitrate: '40M',
    audioSampleRate: 48000,
    maintainAspect: true,
    requiresPro: true,
  },
];